all:
  vars:
    # Для первого запуска укажите пользователя, который уже может sudo без пароля.
    # После применения роли можно переключиться на пользователя ansible.
    ansible_user: ubuntu
    ansible_become: true
  children:
    mobilepark:
      hosts:
        mp-node-1:
          ansible_host: 192.168.56.11
        mp-node-2:
          ansible_host: 192.168.56.12
        mp-node-3:
          ansible_host: 192.168.56.13

    swarm_managers:
      hosts:
        mp-node-1:

    swarm_workers:
      hosts:
        mp-node-2:
        mp-node-3:
